name: CraftingTable
main: brs.craftingtable.CraftingTable
version: 1.0
api-version: 1.21

commands:
  craft:
    description: Çalışma masası açar.
    usage: /craft
    aliases: [ct]
    permission: craftingtable.use

permissions:
  craftingtable.use:
    default: true
